sudo: required
services:
  - docker


before_install:
  - docker build -t srihareendra/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true srihareendra/docker-react2 npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-2-408029887137"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECURE_KEY